name: Release
on: 
  push:
    tags:
    - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - name: Archive Release
      uses: thedoctor0/zip-release@main
      with:
        type: 'tar'
        filename: 'resources.tar.gz'
        exclusions: '*.git* README.md'
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "resources.tar.gz"