name: Release
on: 
  push:
    tags:
    - 'v*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - name: Move release files
      run: |
        mkdir package
        mv certs/* package/certs
        mv golem-certs/* package/golem-certs
        mv whitelist/* package/whitelist
    - name: Archive Release
      uses: thedoctor0/zip-release@0.6.2 # last working version
      with:
        type: 'tar'
        filename: 'resources.tar.gz'
        directory: 'package'
    - uses: ncipollo/release-action@v1
      id: create_release
      with:
        artifacts: "resources.tar.gz"
        prerelease: true

    - name: Build .deb
      id: deb
      run: |
        chmod +x debian/build-deb.sh
        ./debian/build-deb.sh ${{ github.ref }}
    - name: Upload Release Deb
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ steps.deb.outputs.deb }}
        asset_name: ${{ steps.deb.outputs.deb }}
        asset_content_type: application/vnd.debian.binary-package
